development:
  adapter: postgresql
  encoding: unicode
  database: geo_query_development
  pool: 5
  username: eddybanks
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: geo_query_test
  pool: 5
  username: eddybanks
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: geo_query_production
  pool: 5
  username: eddybanks
  password:
